CloudHealth/cht_api_guide

examples/ruby/get_lifetime_costs.rb

Enable API calls over SSL

---

README.md

Fixing minor redundancy, example, and typos

Fixing minor redundancy, example, and typos

---

examples/ruby/metrics_push.rb

Adding an example to push metrics using CloudHealth's Metrics API

---

metrics_api.md

Trello: https://trello.com/c/i1KK1UQi

Updated metrics API doc for file system support. (Card 7034)

---

examples/python/export_csv.py

Trello Card: https://trello.com/c/wTDjPqDt/7574-update-sample-python-script-per-zd-1419

Remove print statement that does not prepend month

---

README.md
account_api.md

AWS Account API

---

account_api.md

**Description:**
https://trello.com/c/5pgt41s4/4607-support-ticket-appdynamics-nomethoderror-undefined-method-has-key-for-assume-role-arn-string-when-attempting-to-create-account-u
**Review:**

adding curl examples for account api

---

perspectives_api.md

API Updates: Index operation, include_version, check_version

API Updates: Index operation, include_version, check_version

---

partner_customer_api.md

Partner customer API:
* Add field `classification`.
* Fix typos.
* Improve formatting.

Partner customer API: Add field classification

---

partner_api.md

This one's just been annoying me for a while.

Fix formatting in partner api guide

---

README.md

At the request of Chris Suchy.

[PLAT-846] Mention internal Ids in Asset API

---

README.md
partner_customer_api.md

* Fixed incorrect capitalization of address attributes in Partner
Account Creation API
* Added Azure as supported provider in Asset API

Fix incorrect capitalization and add Azure

---

account_api.md

Jira: https://cloudhealthtech.atlassian.net/browse/AWS-1874
Just adding a space to make the heading be parsed as a heading.

[AWS-1874] Correct Markdown heading formatting

---

partner_customer_api.md

Wrote a fix to make State and Country work as lowercase and better parse state/country strings. Changed the doc to reflect that.
Related JIRA card: https://github.com/CloudHealth/cloudpercept/pull/13041

Update to casing based on ENG-8788/ENG-8789

---

Gemfile.lock
_config.yml
css/style.scss

Submitting SCSS fix

---

README.md
_config.yml
_documentation/getting_started.md
_partner/customer-account-add.md
_reporting/report-data-format.md
_sass/_main.scss
_tagging/post-tags-for-assets.md
js/search.js
search.html

* Fixed minor bugs
* Improved search index to capture parameter names
* Added note about Australian state names

Bug fixes, search improvement, and Partner API clarification

---

Gemfile.lock
_asset/asset-query-examples.md
_layouts/default.html
_metrics/about-metrics-api.md
_metrics/metrics-post-data-format.md
_partner/customer-account-add.md
_reporting/add-filters-to-report-query.md
_sass/_main.scss
js/main.js

* Azure Asset API example
* Partner Customer API bug fix
* Mobile view fix
* Reporting API bug fix

Examples, clarifications, and mobile fix

---

_account/aws-account-update.md

Change `assume_role` to `assume_role_arn`.

Fix `aws_account` authentication `assume_role_arn`

---

_asset/about-asset-api.md
_asset/asset-query-examples.md
_asset/get-asset-list.md
_asset/get-specific-asset.md
_asset/query-asset-object.md

New `fields` parameter in the Assets API. Added examples on how to use
the `fields` parameter and cleaned up existing examples.

Asset api enhancements

---

README.md
_account/aws-account-add.md
_assignment/about-assignment-api.md
_assignment/aws-account-assignment-create.md
_assignment/aws-account-assignment-delete.md
_assignment/aws-account-assignment-read-single.md
_assignment/aws-account-assignment-read.md
_assignment/aws-account-assignment-update.md
_metrics/metrics-post-data-format.md
_metrics/metrics-rate-limits.md
_partner/linkage-post-data-format.md

Updated example snippet for AWS account creation. Added new description
snippets. Fixed a broken link.

Updated Account API example and topic descriptions

---

_partner/cust-statement-read-multiple.md
_partner/cust-statement-read-single.md
_partner/customer-account-add.md
_partner/customer-account-delete.md
_partner/customer-account-modify.md
_partner/get-all-customers.md
_partner/get-customer-reports.md
_partner/get-single-customer.md
_partner/list-govcloud-linkages.md
_partner/update-single-govcloud-linkage.md

Updated inconsistent quote style in Partner API documentation. Also
fixed incorrect endpoint definition.

Update quote styled in Partner API and fixing bug

---

_partner/post-govcloud-account-linkage.md
_partner/update-single-govcloud-linkage.md

Fixed errors in the GovCloud API sample requests.

Govcloud API fixes

---

_perspectives/create-perspective-schema.md
_perspectives/delete-perspective-schema.md
_perspectives/get-all-perspectives.md
_perspectives/get-perspective-schema.md

* Fixed inconsistent Perspective schema examples in the doc.
* Revised section that discussed deletion options

Perspective schema and deletion options

---

_price-book/price-book-xml-data-format.md

Made small changes and fixes to custom price book documentation.

Custom Price Book fixes

---

_price-book/price-book-xml-data-format.md

Fixed typo in custom price books.

Custom Price Books fix

---

_price-book/price-book-xml-data-format.md

Fixed typo and added additional information.

Custom Price Book edits

---

_partner/get-customer-assets.md
_partner/get-customer-reports.md

Fixed minor errors in the Partner API reporting and asset collection endpoints.

Partner API endpoint fixes

---

_partner/customer-account-add.md

Fixed default value of the enabled parameter, which was previously incorrect.

Customer Account Add API fix

---

_asset/query-asset-object.md

Fixed the incorrect specification of `is_active` as an endpoint
parameter

Fixed incorrect specification of is_active parameter

---

_azure-partner/about-partner-api.md
_azure-partner/customer-account-add.md
_azure-partner/customer-account-modify.md
_azure-partner/get-all-customers-list.md
_azure-partner/get-all-customers.md
_azure-partner/get-customer-id.md
_azure-partner/get-single-customers-list.md
_azure-partner/get-single-customers.md
_config.yml

API documentation for creating Microsoft CSP partner customers.

Azure Partner API

---

_azure-partner/customer-account-add.md
_azure-partner/customer-account-modify.md
_azure-partner/get-all-customers-list.md
_azure-partner/get-all-customers.md
_azure-partner/get-single-customers-list.md
_azure-partner/get-single-customers.md

Fixed incorrect response bodies.

Azure Partner API fix

---

_azure-assignment/about-assignment-api.md
_azure-assignment/azure-account-assignment-create.md
_azure-assignment/azure-account-assignment-delete.md
_config.yml

Azure Partner Customer Account Assignment API

---

_azure-assignment/azure-account-assignment-create.md

Fixed incorrect parameter name in response body.

Azure API fix

---

_azure-assignment/azure-account-assignment-read-single.md
_azure-assignment/azure-account-assignment-read.md

Azure Account Assignment API

---

_azure-assignment/azure-account-assignment-create.md
_azure-assignment/azure-account-assignment-delete.md
_azure-assignment/azure-account-assignment-read-single.md

Azure Account Assignment API fixes

---

_tagging/about-tagging-api.md

Update for GCP's new support of custom tagging.

GCP support for custom tagging

---

_asset/query-asset-object.md
_metrics/get-metrics-for-an-asset.md

Clarified default values and behavior of `page` and `per_page`
parameters in the Asset API.

Clarification of page and per_page parameters

---

_partner/cust-statement-read-multiple.md
_partner/cust-statement-read-single.md

Updated response bodies for for updates to support multiple clouds.

Partner Statement API update

---

_partner/get-client-api-id.md

Added programatic means to obtaining the Client API ID.

Client API ID update

---

_config.yml
_sso/configure-sso.md
_sso/delete-sso-configuration.md
_sso/get-pending-domains.md
_sso/get-sso-configuration.md
_sso/validate-sso-domains.md

Documenting a new endpoint for SSO configuration. API allows creation, update, and deletion of SSO configurations and validation of pending SSO domains.

SSO Configuration API

---

_organization/create-org.md
_organization/org-account-assignment-add.md
_organization/org-account-assignment-remove.md
_organization/org-account-assignment-replace.md
_organization/org-modify.md

Fixed typos in request and response bodies.

Organization API fix

---

_perspectives/update-perspective-schema.md

Fixed typo in Perspectives API.

Typo fix to Perspectives API

---

_billing-rules/get-rule-id.md
_price-book/price-book-xml-data-format.md

New element for Savings Plan in XML.

Custom Price Book update

---

_asset/query-asset-object.md

Update for Azure Policy support

Asset API Update

---

_gcp-account/billing-account-add.md
_gcp-account/billing-account-modify.md
_gcp-account/encode-json-key.md
_gcp-account/gcp-account-delete.md
_gcp-account/get-all-accounts-list.md
_gcp-account/get-single-accounts-list.md

Updated to add additional instructions for the JSON private key.

GCP Billing Accounts API update

---

Gemfile.lock
_organization/org-account-assignment-add-v2.md
_organization/org-account-assignment-append.md
_organization/org-account-assignment-remove-v2.md
_organization/org-account-assignment-replace-v2.md

Edited the following topics to remove incorrect syntax and/or parameters.
* Assign Account to Organization
* Replace Existing Organization Account Assignment
* Delete Existing Organization Account Assignment

Organizations API Updates

---

_partner/cust-statement-read-multiple.md
_partner/cust-statement-read-single.md

Updated the single and multiple customer statement commands to reflect new paramters added in PAR-2333 Improve API consumer experience for customer_statements route.

Updates for PAR-2333

---

Gemfile.lock
_account/aws-account-read-single.md
_account/aws-account-update.md
package-lock.json

mbindu-HC923

---

_perspectives/add-dynamic-group.md

Example output was incorrect, updated the example for accuracy.

Update example for Add Dynamic Group to Existing Perspective

---

_documentation/getting_started.md

Removed an admonition that added no value at the end of the intro. Added an admonition to the start to draw more attention to the GraphQL guide's availability

Modified admonitions

---

_organization/create-org-v2.md
_organization/org-account-assignment-add-v2.md
_organization/org-account-assignment-append.md
_organization/org-account-assignment-remove-v2.md
_organization/org-account-assignment-replace-v2.md
_organization/org-modify-v2.md

Added comma and updated string value wherever required.

Fixed issues

---

_assignment/about-assignment-api.md
_assignment/aws-account-assignment-create-v2.md
_assignment/aws-account-assignment-delete-v2.md
_assignment/aws-account-assignment-read-single-v2.md
_assignment/aws-account-assignment-read-v2.md
_assignment/aws-account-assignment-update-v2.md
_partner/customer-account-add.md
_partner/get-client-api-id.md
_price-book/price-book-get-all-customers.md
_price-book/price-book-get-all.md

- Added target_client_api_id to commands that now support it. 
- Removed some outdated text that is no longer accurate.
- Edited example requests to ensure accuracy.

Added new query parameters, edited examples

---

_reporting/add-dimensions-and-measures-to-report-query.md
_reporting/add-filters-to-report-query.md
_reporting/get-dimensions-measures.md
_reporting/get-one-custom-report.md
_reporting/get-one-standard-report.md
_reporting/get-report-list.md
_reporting/get-report-query.md
_reporting/get-standard-reports.md
_reporting/query-response-size-optimization.md
_reporting/understand-time-filters.md

Query Response Size Optimization article added to the guide. Changed the order of the other articles in the 'Reporting' section in order to include the new article.

Query Response Size Optimization

---

_perspectives/update-perspective-schema.md

Add section in Update perspective scheme that clarifies how to remove a static group from a perspective.

Document how to remove static group from perspective

---

_price-book/price-book-xml-data-format.md

Replaced CHBillingRules with CHTBillingRules.

Updated Price Book Specification field

---

_gcp-account/billing-account-add.md

https://help.cloudhealthtech.com/graphql-api/#update-gcp-project-details

Added Project API details

---

_sso/get-sso-configuration.md

Retrieve SSO configuration API Endpoint updated.

Endpoint updated.

---

.gitignore
_price-book/price-book-test.md

Fixing issues blocking publication of the Test New Price Book API.

Publish test new price book api
